title: "Bestiary"
author: ""
description: "A searchable D&D 5e creature list."
url: "https://sgtbackpack.github.io/dnd_5e_monster_list"
source-url: "https://sgtbackpack.github.io/dnd_5e_monster_list"
baseurl: "/dnd_5e_monster_list"
exclude: ['Rakefile', 'README.md']
collections:
  creatures:
    output: true
    permalink: "/creature/:name"
  tags:
    output: true
    permalink: "/tag/:name"
